### ISSUE TITLE
Elements' getSourceId() method has been deprecated. Use getCanonicalId() instead.

### ISSUE THREAD

**Issue by smcguire1** [Goldinteractive/craft3-publisher#10]
Use of the plugin is generating Deprecation Warnings when scheduling Drafts for publication.

Elements' getSourceId() method has been deprecated. Use getCanonicalId() instead.

Stack Trace:
13	Deprecation error: Elements’ getSourceId() method has been deprecated. Use getCanonicalId() instead.
	Called from /craft/vendor/craftcms/cms/src/base/Element.php:2320
12	craft\elements\Entry::getSourceId()
	Called from /craft/vendor/yiisoft/yii2/base/Component.php:140
11	craft\elements\Entry::__get("sourceId")
	Called from /craft/vendor/craftcms/cms/src/base/Element.php:1736
10	craft\elements\Entry::__get("sourceId")
	Called from /craft/vendor/goldinteractive/craft3-publisher/src/controllers/EntriesController.php:53
9	goldinteractive\publisher\controllers\EntriesController::actionSave()
8	call_user_func_array([goldinteractive\publisher\controllers\EntriesController, "actionSave"], [])
	Called from /craft/vendor/yiisoft/yii2/base/InlineAction.php:57
7	yii\base\InlineAction::runWithParams([])
	Called from /craft/vendor/yiisoft/yii2/base/Controller.php:181
6	goldinteractive\publisher\controllers\EntriesController::runAction("save", [])
	Called from /craft/vendor/yiisoft/yii2/base/Module.php:534
5	craft\web\Application::runAction("publisher/entries/save", [])
	Called from /craft/vendor/craftcms/cms/src/web/Application.php:287
4	craft\web\Application::runAction("publisher/entries/save", [])
	Called from /craft/vendor/craftcms/cms/src/web/Application.php:596
3	craft\web\Application::_processActionRequest(craft\web\Request)
	Called from /craft/vendor/craftcms/cms/src/web/Application.php:266
2	craft\web\Application::handleRequest(craft\web\Request)
	Called from /craft/vendor/yiisoft/yii2/base/Application.php:392
1	craft\web\Application::run()
	Called from /craft/web/index.php:21

**Comment by lukasNo1** [comment]
This is fixed now in the new [release](https://github.com/Goldinteractive/craft3-publisher/releases/tag/2.1.0) that requires craft ^3.7
