### ISSUE TITLE
Does not work for non Admins

### ISSUE THREAD

**Issue by mark-chief** [Goldinteractive/craft3-publisher#2]
The plugin appears to not work for users that are not full Admin group.

The schedule publish panel doesn't not display in the entry.

Thanks

**Comment by christianruhstaller** [comment]
A user needs to have the correct rights. If a user can not publish drafts he will not be allowed to schedule any publishings. Did you check if the rights are set correctly?

**Comment by mark-chief** [comment]
The user group in question appears to have full permissions in that section. 
![Screen Shot 2019-03-18 at 10 24 44](https://user-images.githubusercontent.com/18699249/54523826-4edc5600-4968-11e9-8eca-161c054184ca.png)

**Comment by christianruhstaller** [comment]
The problem was that Craft changed the way it handles permissions and co. Before the change Craft checked for the id and currently it checks for the uid.

The release 1.1.0 fixes this problem.
https://github.com/Goldinteractive/craft3-publisher/releases/tag/1.1.0
