### ISSUE TITLE
Craft 3.2 Compatibility

### ISSUE THREAD

**Issue by lukasNo1** [Goldinteractive/craft3-publisher#3]
The plugin currently doesnt work under Craft 3.2 (tested with 3.2.4.1)

Craft 3.2 made some changes to drafts and the according functions.
These need to be reflected in the plugin.

Declaration of goldinteractive\publisher\elements\db\EntryPublishQuery::draftId(int $value) must be compatible with craft\elements\db\ElementQuery::draftId(?int $value = NULL)

**Comment by christianruhstaller** [comment]
This is not the only problem with the 3.2 version. There are some conceptual things we need to consider as the drafts do have quite a different behavior than before.

For this I opened an issue https://github.com/craftcms/cms/issues/4642 with Craft CMS.

**Comment by christianruhstaller** [comment]
The release 2.0.0 should now be compatible with Craft 3.2. 

https://github.com/Goldinteractive/craft3-publisher/releases/tag/2.0.0
