### ISSUE TITLE
Base table or view not found: Table 'craft_entrypublishes' doesn't exist

### ISSUE THREAD

**Issue by romainpoirier** [Goldinteractive/craft3-publisher#5]
### Description

I can't use the plugin. After install, the error bellow show up each time I try to display an Entry page.

I can see the `entrypublishes`' table  doesn't exists. This table wasn't installed during the plugin installation (using `composer require`), neither during the enable of the plugins from `/admin/settings/plugins`.

Solution was to uninstall the plugin unfortunately.

```
Database Exception – yii\db\Exception
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'craft_entrypublishes' doesn't exist
The SQL being executed was: SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`siteId`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `entrypublishes`.*
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`
FROM `craft_elements` `elements`
INNER JOIN `craft_entrypublishes` `entrypublishes` ON `entrypublishes`.`id` = `elements`.`id`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
WHERE (`entrypublishes`.`sourceId`=55) AND (`elements_sites`.`siteId`='1') AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL) AND (`elements_sites`.`enabled`=TRUE) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL)
ORDER BY `elements`.`dateCreated` DESC) `subquery`
INNER JOIN `craft_entrypublishes` `entrypublishes` ON `entrypublishes`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
ORDER BY `elements`.`dateCreated` DESC
Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'craft_entrypublishes' doesn't exist
)
↵
Caused by: PDOException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'craft_entrypublishes' doesn't exist
in /vendor/yiisoft/yii2/db/Command.php at line 1293
```

### Additional info

- Craft version: Craft Pro 3.4.18
- PHP version: 7.1.30
- Database driver & version: MySQL 5.7.26

**Comment by romainpoirier** [comment]
I tried to install the plugin on a brand new test website (Craft Solo 3.4.19.1), and got the exact same error. So I guess every new user of this plugin wouldn't be able to use it.

**Comment by christianruhstaller** [comment]
Could you try it with following version: 2.0.3
On 2.0.4 there were some updates on the installation routine and it seems that this broke it. 
As the 2.0.4 version just changes the installation routine it should not be a problem to keep going with that version for now.

As for the bug we'll look into it and report back.

**Comment by romainpoirier** [comment]
I tried today to install from 2.0.3 version, but got the same database error.

**Comment by christianruhstaller** [comment]
I looked and it and it seems that somehow the installation migration was messed up.
Could you install "dev-master" and see if it's working now?

**Comment by romainpoirier** [comment]
Thank you, as from the dev-master version the database error is gone.

**Comment by christianruhstaller** [comment]
Fine. I released a new version 2.0.5 with the fix.

https://github.com/Goldinteractive/craft3-publisher/releases/tag/2.0.5

**Comment by romainpoirier** [comment]
**UPDATE:** while it was working on dev server (from `dev-master` to `2.0.5`), after deploy on staging server I still got the error (`craft_entrypublishes' doesn't exist`). How can I force the install of this table on staging (and then on production)?

**Comment by christianruhstaller** [comment]
An install is forced by uninstalling and installing the plugin again.
**Attention: this will delete the possible existing craft_entrypublishes**

It seems that you are currently in a strange state of installation. 
Can you report if the reinstallation helps?

**Comment by romainpoirier** [comment]
Thank you, the reinstallation helps. This is working fine now.
