### ISSUE TITLE
Does publish, but doesn't refresh cache, so entry isn't on front-end

### ISSUE THREAD

**Issue by Friksel** [Goldinteractive/craft3-publisher#6]
The point of using this plugin is to break through the static caching when a new entry is published. But this doesn't seem to work in at least the latest Craft version.

Triggering `./craft publisher/publish` does update the pending message on the panel near the entry in Craft CP as if it's published on the right time, so the timing is right, but it's not re-saving the entry so it cannot break through the static caching making the new entry still isn't visible on frontend when updating the page, eventhough the icon is green in the CP and the pending-message dissappeared in the CP.

When manually saving the entry after the postdate/time everything works fine with static caching, so not sure what this plugin is doing instead, but it's for some reason not making the static cache renew and obviously isn't re-saving the entry to break through the caching either.

There is no example on the readme on some special cache key or whatever, so I would say all static cache types and keys should work together with using this plugin? But unfortunately it's not in practise.

I like the idea of this plugin and would like to use it on a project, but it doesn't seem to work with static caching and that's the whole point of using this plugin over default post-date behaviour of Craft.

**Am I missing something here? Or is there an issue or has something changed in Craft making the plugin to fail?**

Thanks in advance

Publisher version: 2.0.5
Craft version: 3.4.27

**Comment by lukasNo1** [comment]
The problem seems to be on status change of an entry. Meaning only the cache of the saved entry will be cleared and not the cache of other sites too, where it potentially needs to be displayed in the frontend.

A solution would be to clear the whole Template Cache on status change of an entry.

Can you confirm this problem is only upon publishing a previously deactivated entry? (Status change).
Content updates shouldn't be a problem.

**Comment by Friksel** [comment]
Sorry for the late response. So far I couldn't find the time to answer your question. I come back to this.

**Comment by lukasNo1** [comment]
The issue seems to be resolved in the new craft version 3.5.0, where they implemented a new "cache invalidate" strategy.
