### ISSUE TITLE
Cron Question

### ISSUE THREAD

**Issue by jpwdesigns** [Goldinteractive/craft3-publisher#8]
Is it necessary to run the cron every minute? Would it cause any issues running once every 5 minutes etc...?

**Comment by christianruhstaller** [comment]
Currently the check depends on the correct minute to publish the correct entry. So yes currently it's required.
What is the problem with that with your setup?

**Comment by jpwdesigns** [comment]
No problem at all! Just curious. I’m cautious about server load. Thanks for the great plugin.
