### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by michaelpelletier** [Goldinteractive/craft3-publisher#9]
Every single entry just says 
<img width="374" alt="Screen Shot 2021-08-17 at 8 41 10 AM" src="https://user-images.githubusercontent.com/1640601/129727258-059a6029-a263-42a8-a032-1e5203929126.png">

With seemingly no way to add more. The lack of documentation, screenshots, usage, etc makes it literally impossible to tell if I have something configured wrong or if the plugin is just broken.

**Comment by brycekirk** [comment]
I feel the same way.

1. Go to an entry and create a draft
2. Make whatever edits you need
3. Set a post date in the future
4. Click _Save draft_
5. Go back into the entry and you should see the pending publish date
6. Set up the cron job as per the readme
